// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/urfave/cli/v2"
)

// Injectors from wire.go:

func Wire() (*cli.App, error) {
	provider, err := NewConfigProvider()
	if err != nil {
		return nil, err
	}
	config, err := NewCLIConfig(provider)
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase()
	if err != nil {
		return nil, err
	}
	openAIQAClient := NewOpenAIQAClient(config, db)
	app := NewCLI(openAIQAClient)
	return app, nil
}
