// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/lunabrain-ai/lunabrain/pkg/store/cache"
	cli2 "github.com/lunabrain-ai/lunapipe/internal/cli"
	"github.com/lunabrain-ai/lunapipe/internal/config"
	"github.com/lunabrain-ai/lunapipe/internal/log"
	"github.com/lunabrain-ai/lunapipe/internal/openai"
	"github.com/urfave/cli/v2"
)

// Injectors from wire.go:

func Wire(cacheConfig cache.Config) (*cli.App, error) {
	localCache, err := cache.NewLocalCache(cacheConfig)
	if err != nil {
		return nil, err
	}
	provider, err := config.NewProvider(localCache)
	if err != nil {
		return nil, err
	}
	openaiConfig, err := openai.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	logConfig, err := log.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	localConfigurator := config.NewConfigurator(localCache)
	app := cli2.New(openaiConfig, logConfig, localConfigurator)
	return app, nil
}
