// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/lunabrain-ai/lunapipe/internal/config"
	"github.com/urfave/cli/v2"
)

// Injectors from wire.go:

func Wire() (*cli.App, error) {
	provider, err := config.NewConfigProvider()
	if err != nil {
		return nil, err
	}
	configConfig, err := config.NewOpenAIConfig(provider)
	if err != nil {
		return nil, err
	}
	openAIQAClient := NewOpenAIQAClient(configConfig)
	logConfig, err := config.NewLogConfig(provider)
	if err != nil {
		return nil, err
	}
	app := NewCLI(openAIQAClient, logConfig)
	return app, nil
}
